compileAll: exer2_main.o exer2.o exer1.o 
	gcc -o exe2 exer2_main.o exer2.o exer1.o 

exer2_main.o: exer2_main.c
	gcc -c exer2_main.c

exer2.o: exer2.c
	gcc -c exer2.c

exer1.o: exer1.c 
	gcc -c exer1.c
